# Numpy Basic


Consider the below code to answer further questions:
```python 
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```
#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there **is a difference** between the data types of `list_` and `array_list`.

Let’s break it down:

---

### 🔍 **Explanation:**

- `list_` is a regular **Python list** of strings.
- `array_list` is a **NumPy array** created from that list, and NumPy arrays have their own **dtype** for elements (in this case, likely `'str'` or `'U1'`, depending on the data).

---

### ✅ **Code to Print Data Types:**

In [1]:
import numpy as np

# Note: Fixing quotes to standard ones
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))
print("Data type of elements in array_list:", array_list.dtype)

Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>
Data type of elements in array_list: <U1


---

### 🖥️ **Expected Output:**

```
Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>
Data type of elements in array_list: <U1
```

---

### 📌 Summary:

| Variable      | Type                | Element Type     |
|---------------|---------------------|------------------|
| `list_`       | `list` (Python)     | `str`            |
| `array_list`  | `numpy.ndarray`     | NumPy string type (like `<U1`) |

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

Sure! Here's how you can print the **data type of each element** in both `list_` and `array_list`:

---

### ✅ **Code:**

In [3]:
import numpy as np

# Define list and array (fixed quotes)
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of each element in list_
print("Data types in list_:")
for i, element in enumerate(list_):
    print(f"Element {i}: {element} -> {type(element)}")

print("\nData types in array_list:")
for i, element in enumerate(array_list):
    print(f"Element {i}: {element} -> {type(element)}")

Data types in list_:
Element 0: 1 -> <class 'str'>
Element 1: 2 -> <class 'str'>
Element 2: 3 -> <class 'str'>
Element 3: 4 -> <class 'str'>
Element 4: 5 -> <class 'str'>

Data types in array_list:
Element 0: 1 -> <class 'numpy.str_'>
Element 1: 2 -> <class 'numpy.str_'>
Element 2: 3 -> <class 'numpy.str_'>
Element 3: 4 -> <class 'numpy.str_'>
Element 4: 5 -> <class 'numpy.str_'>


---

### 🖥️ **Expected Output:**

```
Data types in list_:
Element 0: 1 -> <class 'str'>
Element 1: 2 -> <class 'str'>
Element 2: 3 -> <class 'str'>
Element 3: 4 -> <class 'str'>
Element 4: 5 -> <class 'str'>

Data types in array_list:
Element 0: 1 -> <class 'numpy.str_'>
Element 1: 2 -> <class 'numpy.str_'>
Element 2: 3 -> <class 'numpy.str_'>
Element 3: 4 -> <class 'numpy.str_'>
Element 4: 5 -> <class 'numpy.str_'>
```

---

### 🔍 **Summary:**

- Elements in `list_` are regular Python **`str`**.
- Elements in `array_list` are **NumPy string objects** (`numpy.str_`), which behave similarly but are part of NumPy's internal type system.

#### Q3. Considering the following changes in the variable, array_list:
```python 
array_list = np.array(object = list_, dtype = int)
```

#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

Consider the below code to answer further questions:
```python 
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

Yes, there **will be a difference** in the data types of elements in `list_` and `array_list` after you explicitly convert `array_list` to `dtype=int`.

Let’s go step by step.

---

## ✅ **Part 1: list_ vs array_list with `dtype=int`**

In [5]:
import numpy as np

# Define original list
list_ = ['1', '2', '3', '4', '5']

# Convert to NumPy array of integers
array_list = np.array(object=list_, dtype=int)

# Print data types of each element in list_
print("Data types in list_:")
for i, element in enumerate(list_):
    print(f"Element {i}: {element} -> {type(element)}")

print("\nData types in array_list (with dtype=int):")
for i, element in enumerate(array_list):
    print(f"Element {i}: {element} -> {type(element)}")

Data types in list_:
Element 0: 1 -> <class 'str'>
Element 1: 2 -> <class 'str'>
Element 2: 3 -> <class 'str'>
Element 3: 4 -> <class 'str'>
Element 4: 5 -> <class 'str'>

Data types in array_list (with dtype=int):
Element 0: 1 -> <class 'numpy.int64'>
Element 1: 2 -> <class 'numpy.int64'>
Element 2: 3 -> <class 'numpy.int64'>
Element 3: 4 -> <class 'numpy.int64'>
Element 4: 5 -> <class 'numpy.int64'>


---

### 🖥️ **Expected Output:**

```
Data types in list_:
Element 0: 1 -> <class 'str'>
Element 1: 2 -> <class 'str'>
Element 2: 3 -> <class 'str'>
Element 3: 4 -> <class 'str'>
Element 4: 5 -> <class 'str'>

Data types in array_list (with dtype=int):
Element 0: 1 -> <class 'numpy.int64'>
Element 1: 2 -> <class 'numpy.int64'>
Element 2: 3 -> <class 'numpy.int64'>
Element 3: 4 -> <class 'numpy.int64'>
Element 4: 5 -> <class 'numpy.int64'>
```

---

## ✅ **Part 2: `num_list` and `num_array` Setup**

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Type of num_list:", type(num_list))
print("Type of num_array:", type(num_array))
print("Shape of num_array:", num_array.shape)
print("Data type of elements in num_array:", num_array.dtype)

Type of num_list: <class 'list'>
Type of num_array: <class 'numpy.ndarray'>
Shape of num_array: (2, 3)
Data type of elements in num_array: int64


---

### 🔍 Summary:

| Variable     | Type                 | Element Type      |
|--------------|----------------------|-------------------|
| `list_`      | `list`               | `str`             |
| `array_list` | `numpy.ndarray`      | `int` (e.g., `int64`) |
| `num_list`   | `list` of `list`s    | `int`             |
| `num_array`  | `numpy.ndarray` (2D) | `int`             |

Let me know if you’d like to reshape, flatten, or perform operations on `num_array` next!

#### Q4. Write a code to find the following characteristics of variable, num_array:
- (i) shape
- (ii) size

In [ ]:
---

### ✅ **Code:**

In [9]:
import numpy as np

# Given 2D list
num_list = [[1, 2, 3], [4, 5, 6]]

# Convert to NumPy array
num_array = np.array(object=num_list)

# (i) Shape of the array
print("Shape of num_array:", num_array.shape)

# (ii) Size (total number of elements)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


---

### 🖥️ **Expected Output:**

```
Shape of num_array: (2, 3)
Size of num_array: 6
```

---

### 🔍 Explanation:

- **Shape:** `(2, 3)` means 2 rows and 3 columns.
- **Size:** `6` is the total number of elements (2 × 3).

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

Sure! You can use the `numpy.zeros()` function to create a **3×3 matrix of zeros**.

---

### ✅ **Code:**

In [2]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

# Print the matrix
print("3x3 Zero Matrix:")
print(zero_matrix)

3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---

### 🖥️ **Expected Output:**

```
3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

---

### 🔍 Notes:
- By default, the elements are of `float` type.
- If you want integers instead, you can specify:  
  `np.zeros((3, 3), dtype=int)`


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

You can easily create an identity matrix using the `numpy.identity()` or `numpy.eye()` function.

---

### ✅ **Code (Using `np.identity`)**:

In [4]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Print the matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### ✅ **Alternative Code (Using `np.eye`)**:

```python
identity_matrix = np.eye(5)
print("5x5 Identity Matrix using np.eye:")
print(identity_matrix)
```

---

### 🖥️ **Expected Output:**

```
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
```

---